# Generated by Django 5.0.1 on 2024-01-31 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='band',
            name='biography',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('RAP', 'Rap'), ('SP', 'Synth'), ('AR', 'Alternative')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
